apiVersion: v1
kind: Service
metadata:
  name: cli
  namespace: {{ .Release.Namespace }}
spec:
  loadBalancerIP: {{ .Values.ingress.addr }}
  externalIPs:
  - {{ .Values.ingress.addr }}
  ports:
  - name: "api"
    port: 7054
    protocol: TCP
  selector:
    service: {{ .Release.Name }}-cli
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    service: {{ .Release.Name }}-cli
  name: {{ .Release.Name }}-cli
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    service: {{ .Release.Name }}-cli
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-cli
      namespace: {{ .Release.Namespace }}
    spec:
      hostAliases:
      - ip: "{{ .Values.fabricOrderer.addr }}"
        hostnames:
        - "orderer.{{ .Values.fabricOrderer.orgDomain }}"
      containers:
      - command:
#        - echo
        - /bin/bash
        - -c
        - "while true; do sleep 30; done;"
#        command: [ "/bin/bash", "-c", "--" ]
#        args: [ "while true; do sleep 30; done;" ]
        env:
          - name: CORE_PEER_TLS_ENABLED
            value: "false"
          #- name: CORE_PEER_TLS_CERT_FILE
          #  value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.crt
          #- name: CORE_PEER_TLS_KEY_FILE
          #  value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.key
          #- name: CORE_PEER_TLS_ROOTCERT_FILE
          #  value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/ca.crt
          - name: CORE_VM_ENDPOINT
            value: unix:///var/run/docker.sock
          - name: GOPATH
            value: /opt/gopath
          - name: CORE_LOGGING_LEVEL
            value: DEBUG
          - name: CORE_PEER_ID
            value: peer0.{{ .Values.fabricOrg.domain }}
          - name: CORE_PEER_ADDRESS
            value: {{ .Values.ingress.addr }}:7051
          - name: CORE_PEER_LOCALMSPID
            value: {{ .Values.fabricOrg.msp }}
          - name: CORE_PEER_MSPCONFIGPATH
            value: /etc/crypto-config/opensource.com/HLF/crypto-config/peerOrganizations/{{ .Values.fabricOrg.domain }}/peers/peer0.{{ .Values.fabricOrg.domain }}/msp
        image: {{ .Values.fabricCli.image }}:{{ .Values.fabricCli.tag }}
        name: {{ .Release.Name }}-cli
        ports:
        - containerPort: 7054
        volumeMounts:
        - mountPath: /etc/crypto-config
          name: {{ .Release.Name }}-crypto-config
          readOnly: true
      volumes:
      - name: {{ .Release.Name }}-crypto-config
{{ toYaml .Values.cryptoConfigMount | indent 8 }}
